// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/FlatFilers/flatfile-go/core"
)

type CreateAgentsRequest struct {
	EnvironmentId EnvironmentId `json:"-"`
	Body          *AgentConfig  `json:"-"`
}

func (c *CreateAgentsRequest) UnmarshalJSON(data []byte) error {
	body := new(AgentConfig)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateAgentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

type DeleteAgentRequest struct {
	EnvironmentId EnvironmentId `json:"-"`
}

type GetAgentRequest struct {
	EnvironmentId EnvironmentId `json:"-"`
}

type GetAgentLogRequest struct {
	EnvironmentId EnvironmentId `json:"-"`
}

type GetAgentLogsRequest struct {
	EnvironmentId EnvironmentId `json:"-"`
}

type GetEnvironmentAgentExecutionsRequest struct {
	EnvironmentId EnvironmentId          `json:"-"`
	SpaceId       *SpaceId               `json:"-"`
	Success       *SuccessQueryParameter `json:"-"`
	PageSize      *PageSize              `json:"-"`
	PageNumber    *PageNumber            `json:"-"`
}

type GetEnvironmentAgentLogsRequest struct {
	EnvironmentId EnvironmentId          `json:"-"`
	SpaceId       *SpaceId               `json:"-"`
	Success       *SuccessQueryParameter `json:"-"`
	PageSize      *PageSize              `json:"-"`
	PageNumber    *PageNumber            `json:"-"`
}

type ListAgentsRequest struct {
	EnvironmentId EnvironmentId `json:"-"`
}

type GetDetailedAgentLogResponse struct {
	Data *DetailedAgentLog `json:"data,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDetailedAgentLogResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDetailedAgentLogResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDetailedAgentLogResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDetailedAgentLogResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDetailedAgentLogsResponse struct {
	Pagination *Pagination         `json:"pagination,omitempty"`
	Data       []*DetailedAgentLog `json:"data,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDetailedAgentLogsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDetailedAgentLogsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDetailedAgentLogsResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDetailedAgentLogsResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetExecutionsResponse struct {
	Pagination *Pagination  `json:"pagination,omitempty"`
	Data       []*Execution `json:"data,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetExecutionsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetExecutionsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetExecutionsResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetExecutionsResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
