// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/FlatFilers/flatfile-go/core"
)

// Data Retention Policy ID
type DataRetentionPolicyId = string

type DataRetentionPolicyConfig struct {
	Type   DataRetentionPolicyEnum `json:"type,omitempty"`
	Period int                     `json:"period"`

	_rawJSON json.RawMessage
}

func (d *DataRetentionPolicyConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler DataRetentionPolicyConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DataRetentionPolicyConfig(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DataRetentionPolicyConfig) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DataRetentionPolicyResponse struct {
	Data *DataRetentionPolicy `json:"data,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DataRetentionPolicyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DataRetentionPolicyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DataRetentionPolicyResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DataRetentionPolicyResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}
