// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/FlatFilers/flatfile-go/core"
)

type ListEntitlementsRequest struct {
	// The associated Resource ID for the entitlements.
	ResourceId string `json:"-" url:"resourceId"`
}

type ListEntitlementsResponse struct {
	Data []*Entitlement `json:"data,omitempty" url:"data,omitempty"`

	_rawJSON json.RawMessage
}

func (l *ListEntitlementsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListEntitlementsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListEntitlementsResponse(value)
	l._rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListEntitlementsResponse) String() string {
	if len(l._rawJSON) > 0 {
		if value, err := core.StringifyJSON(l._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
