// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/FlatFilers/flatfile-go/internal"
)

type ListEntitlementsRequest struct {
	// The associated Resource ID for the entitlements.
	ResourceId string `json:"-" url:"resourceId"`
}

// An entitlement belonging to a resource
type Entitlement struct {
	// Short name for the entitlement
	Key string `json:"key" url:"key"`
	// Contains conditions or limits for an entitlement
	Metadata interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *Entitlement) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *Entitlement) GetMetadata() interface{} {
	if e == nil {
		return nil
	}
	return e.Metadata
}

func (e *Entitlement) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *Entitlement) UnmarshalJSON(data []byte) error {
	type unmarshaler Entitlement
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = Entitlement(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Entitlement) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type ListEntitlementsResponse struct {
	Data []*Entitlement `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListEntitlementsResponse) GetData() []*Entitlement {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListEntitlementsResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListEntitlementsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListEntitlementsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListEntitlementsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListEntitlementsResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
