// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/FlatFilers/flatfile-go/core"
)

type ListSecrets struct {
	// The Environment of the secret.
	EnvironmentId *EnvironmentId `json:"-" url:"environmentId,omitempty"`
	// The Space of the secret.
	SpaceId *SpaceId `json:"-" url:"spaceId,omitempty"`
	// The Actor of the secret.
	ActorId *ActorIdUnion `json:"-" url:"actorId,omitempty"`
}

// Secret ID
type SecretId = string

// The value of a secret
type Secret struct {
	// The reference name for a secret.
	Name SecretName `json:"name" url:"name"`
	// The secret value. This is hidden in the UI.
	Value SecretValue `json:"value" url:"value"`
	// The Environment of the secret.
	EnvironmentId *EnvironmentId `json:"environmentId,omitempty" url:"environmentId,omitempty"`
	// The Space of the secret.
	SpaceId *SpaceId `json:"spaceId,omitempty" url:"spaceId,omitempty"`
	// The Actor of the secret.
	ActorId *ActorIdUnion `json:"actorId,omitempty" url:"actorId,omitempty"`
	// The ID of the secret.
	Id SecretId `json:"id" url:"id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *Secret) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *Secret) UnmarshalJSON(data []byte) error {
	type unmarshaler Secret
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Secret(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *Secret) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// The name of a secret. Minimum 1 character, maximum 1024
type SecretName = string

// The value of a secret. Minimum 1 character, maximum 1024
type SecretValue = string

type SecretsResponse struct {
	Data []*Secret `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SecretsResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SecretsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecretsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecretsResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SecretsResponse) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// The properties required to write to a secret. Value is the only mutable property. Name, environmentId, spaceId (optional) are used for finding the secret.
type WriteSecret struct {
	// The reference name for a secret.
	Name SecretName `json:"name" url:"name"`
	// The secret value. This is hidden in the UI.
	Value SecretValue `json:"value" url:"value"`
	// The Environment of the secret.
	EnvironmentId *EnvironmentId `json:"environmentId,omitempty" url:"environmentId,omitempty"`
	// The Space of the secret.
	SpaceId *SpaceId `json:"spaceId,omitempty" url:"spaceId,omitempty"`
	// The Actor of the secret.
	ActorId *ActorIdUnion `json:"actorId,omitempty" url:"actorId,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WriteSecret) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WriteSecret) UnmarshalJSON(data []byte) error {
	type unmarshaler WriteSecret
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WriteSecret(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WriteSecret) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}
