// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/FlatFilers/flatfile-go/internal"
	time "time"
)

type CreateSnapshotRequest struct {
	// ID of sheet
	SheetId SheetId `json:"sheetId" url:"-"`
	// Label for the snapshot
	Label *string `json:"label,omitempty" url:"-"`
	// ThreadId for the snapshot
	ThreadId *string `json:"threadId,omitempty" url:"-"`
}

type GetSnapshotRequest struct {
	// Whether to include a summary in the snapshot response
	IncludeSummary bool `json:"-" url:"includeSummary"`
}

type GetSnapshotRecordsRequest struct {
	// Number of records to return in a page
	PageSize *int `json:"-" url:"pageSize,omitempty"`
	// Based on pageSize, which page of records to return
	PageNumber *int `json:"-" url:"pageNumber,omitempty"`
	// Filter records by change type
	ChangeType *ChangeType `json:"-" url:"changeType,omitempty"`
}

type ListSnapshotRequest struct {
	// ID of sheet
	SheetId SheetId `json:"-" url:"sheetId"`
	// ThreadId to filter snapshots by
	ThreadId *string `json:"-" url:"threadId,omitempty"`
}

// Options to filter records in a snapshot
type ChangeType string

const (
	ChangeTypeCreatedSince ChangeType = "createdSince"
	ChangeTypeUpdatedSince ChangeType = "updatedSince"
	ChangeTypeDeletedSince ChangeType = "deletedSince"
)

func NewChangeTypeFromString(s string) (ChangeType, error) {
	switch s {
	case "createdSince":
		return ChangeTypeCreatedSince, nil
	case "updatedSince":
		return ChangeTypeUpdatedSince, nil
	case "deletedSince":
		return ChangeTypeDeletedSince, nil
	}
	var t ChangeType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChangeType) Ptr() *ChangeType {
	return &c
}

type RestoreOptions struct {
	Created bool `json:"created" url:"created"`
	Updated bool `json:"updated" url:"updated"`
	Deleted bool `json:"deleted" url:"deleted"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RestoreOptions) GetCreated() bool {
	if r == nil {
		return false
	}
	return r.Created
}

func (r *RestoreOptions) GetUpdated() bool {
	if r == nil {
		return false
	}
	return r.Updated
}

func (r *RestoreOptions) GetDeleted() bool {
	if r == nil {
		return false
	}
	return r.Deleted
}

func (r *RestoreOptions) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RestoreOptions) UnmarshalJSON(data []byte) error {
	type unmarshaler RestoreOptions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RestoreOptions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RestoreOptions) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type SchemaDiffData = map[string]SchemaDiffEnum

type SchemaDiffEnum string

const (
	SchemaDiffEnumAdded     SchemaDiffEnum = "added"
	SchemaDiffEnumRemoved   SchemaDiffEnum = "removed"
	SchemaDiffEnumUnchanged SchemaDiffEnum = "unchanged"
)

func NewSchemaDiffEnumFromString(s string) (SchemaDiffEnum, error) {
	switch s {
	case "added":
		return SchemaDiffEnumAdded, nil
	case "removed":
		return SchemaDiffEnumRemoved, nil
	case "unchanged":
		return SchemaDiffEnumUnchanged, nil
	}
	var t SchemaDiffEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SchemaDiffEnum) Ptr() *SchemaDiffEnum {
	return &s
}

type SchemaDiffRecord = SchemaDiffData

type Snapshot struct {
	// The ID of the Snapshot.
	Id SnapshotId `json:"id" url:"id"`
	// The ID of the Sheet.
	SheetId SheetId `json:"sheetId" url:"sheetId"`
	// The title of the Snapshot.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// A summary of the Snapshot. This field is only available on the single get snapshot endpoint. It is not available for the list snapshots endpoint.
	Summary *SnapshotSummary `json:"summary,omitempty" url:"summary,omitempty"`
	// The time the Snapshot was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// The actor who created the Snapshot.
	CreatedBy UserId `json:"createdBy" url:"createdBy"`
	// The ID of the thread associated with the snapshot.
	ThreadId *string `json:"threadId,omitempty" url:"threadId,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Snapshot) GetId() SnapshotId {
	if s == nil {
		return ""
	}
	return s.Id
}

func (s *Snapshot) GetSheetId() SheetId {
	if s == nil {
		return ""
	}
	return s.SheetId
}

func (s *Snapshot) GetLabel() *string {
	if s == nil {
		return nil
	}
	return s.Label
}

func (s *Snapshot) GetSummary() *SnapshotSummary {
	if s == nil {
		return nil
	}
	return s.Summary
}

func (s *Snapshot) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Snapshot) GetCreatedBy() UserId {
	if s == nil {
		return ""
	}
	return s.CreatedBy
}

func (s *Snapshot) GetThreadId() *string {
	if s == nil {
		return nil
	}
	return s.ThreadId
}

func (s *Snapshot) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *Snapshot) UnmarshalJSON(data []byte) error {
	type embed Snapshot
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = Snapshot(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Snapshot) MarshalJSON() ([]byte, error) {
	type embed Snapshot
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*s),
		CreatedAt: internal.NewDateTime(s.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *Snapshot) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SnapshotResponse struct {
	Data *Snapshot `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SnapshotResponse) GetData() *Snapshot {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SnapshotResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SnapshotResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SnapshotResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SnapshotResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SnapshotResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SnapshotSummary struct {
	CreatedSince *SummarySection `json:"createdSince,omitempty" url:"createdSince,omitempty"`
	UpdatedSince *SummarySection `json:"updatedSince,omitempty" url:"updatedSince,omitempty"`
	DeletedSince *SummarySection `json:"deletedSince,omitempty" url:"deletedSince,omitempty"`
	// The schema diff between the snapshot and the current sheet schema.
	SchemaDiff SchemaDiffRecord `json:"schemaDiff,omitempty" url:"schemaDiff,omitempty"`
	// The sheet configuration at the time of the snapshot.
	Config *SheetConfig `json:"config,omitempty" url:"config,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SnapshotSummary) GetCreatedSince() *SummarySection {
	if s == nil {
		return nil
	}
	return s.CreatedSince
}

func (s *SnapshotSummary) GetUpdatedSince() *SummarySection {
	if s == nil {
		return nil
	}
	return s.UpdatedSince
}

func (s *SnapshotSummary) GetDeletedSince() *SummarySection {
	if s == nil {
		return nil
	}
	return s.DeletedSince
}

func (s *SnapshotSummary) GetSchemaDiff() SchemaDiffRecord {
	if s == nil {
		return nil
	}
	return s.SchemaDiff
}

func (s *SnapshotSummary) GetConfig() *SheetConfig {
	if s == nil {
		return nil
	}
	return s.Config
}

func (s *SnapshotSummary) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SnapshotSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler SnapshotSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SnapshotSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SnapshotSummary) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SnapshotsResponse struct {
	Data []*Snapshot `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SnapshotsResponse) GetData() []*Snapshot {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SnapshotsResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SnapshotsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SnapshotsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SnapshotsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SnapshotsResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SummarySection struct {
	Total   int            `json:"total" url:"total"`
	ByField map[string]int `json:"byField,omitempty" url:"byField,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SummarySection) GetTotal() int {
	if s == nil {
		return 0
	}
	return s.Total
}

func (s *SummarySection) GetByField() map[string]int {
	if s == nil {
		return nil
	}
	return s.ByField
}

func (s *SummarySection) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SummarySection) UnmarshalJSON(data []byte) error {
	type unmarshaler SummarySection
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SummarySection(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SummarySection) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
