// This file was auto-generated by Fern from our API Definition.

package api

type VersionsPostRequestBody struct {
	// The ID of the Sheet.
	SheetId *SheetId `json:"sheetId,omitempty" url:"-"`
	// Deprecated, creating or updating a group of records together will automatically generate a commitId to group those record changes together.
	ParentVersionId *VersionId `json:"parentVersionId,omitempty" url:"-"`
}
