// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/FlatFilers/flatfile-go/internal"
	time "time"
)

type ListWorkbookCommitsRequest struct {
	// If true, only return commits that have been completed. If false, only return commits that have not been completed. If not provided, return all commits.
	Completed *bool `json:"-" url:"completed,omitempty"`
}

type ListWorkbooksRequest struct {
	// The associated Space ID of the Workbook.
	SpaceId *SpaceId `json:"-" url:"spaceId,omitempty"`
	// Filter by name. Precede with - to negate the filter
	Name *string `json:"-" url:"name,omitempty"`
	// Filter by namespace. Precede with - to negate the filter
	Namespace *string `json:"-" url:"namespace,omitempty"`
	// Filter by label. Precede with - to negate the filter
	Label *string `json:"-" url:"label,omitempty"`
	// Filter by treatment.
	Treatment *string `json:"-" url:"treatment,omitempty"`
	// Include sheets for the workbook (default true)
	IncludeSheets *bool `json:"-" url:"includeSheets,omitempty"`
	// Include counts for the workbook. **DEPRECATED** Counts will return 0s. Use GET /sheets/:sheetId/counts
	IncludeCounts *bool `json:"-" url:"includeCounts,omitempty"`
}

// Properties used to create a new Workbook
type CreateWorkbookConfig struct {
	// The name of the Workbook.
	Name string `json:"name" url:"name"`
	// An optional list of labels for the Workbook.
	Labels []string `json:"labels,omitempty" url:"labels,omitempty"`
	// Space to associate with the Workbook.
	SpaceId *SpaceId `json:"spaceId,omitempty" url:"spaceId,omitempty"`
	// Environment to associate with the Workbook
	EnvironmentId *EnvironmentId `json:"environmentId,omitempty" url:"environmentId,omitempty"`
	// Optional namespace to apply to the Workbook.
	Namespace *string `json:"namespace,omitempty" url:"namespace,omitempty"`
	// Sheets to create on the Workbook.
	Sheets []*SheetConfig `json:"sheets,omitempty" url:"sheets,omitempty"`
	// Actions to create on the Workbook.
	Actions []*Action `json:"actions,omitempty" url:"actions,omitempty"`
	// The Workbook settings.
	Settings *WorkbookConfigSettings `json:"settings,omitempty" url:"settings,omitempty"`
	// Metadata for the workbook
	Metadata interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Treatments for the workbook
	Treatments []WorkbookTreatments `json:"treatments,omitempty" url:"treatments,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateWorkbookConfig) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateWorkbookConfig) GetLabels() []string {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *CreateWorkbookConfig) GetSpaceId() *SpaceId {
	if c == nil {
		return nil
	}
	return c.SpaceId
}

func (c *CreateWorkbookConfig) GetEnvironmentId() *EnvironmentId {
	if c == nil {
		return nil
	}
	return c.EnvironmentId
}

func (c *CreateWorkbookConfig) GetNamespace() *string {
	if c == nil {
		return nil
	}
	return c.Namespace
}

func (c *CreateWorkbookConfig) GetSheets() []*SheetConfig {
	if c == nil {
		return nil
	}
	return c.Sheets
}

func (c *CreateWorkbookConfig) GetActions() []*Action {
	if c == nil {
		return nil
	}
	return c.Actions
}

func (c *CreateWorkbookConfig) GetSettings() *WorkbookConfigSettings {
	if c == nil {
		return nil
	}
	return c.Settings
}

func (c *CreateWorkbookConfig) GetMetadata() interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateWorkbookConfig) GetTreatments() []WorkbookTreatments {
	if c == nil {
		return nil
	}
	return c.Treatments
}

func (c *CreateWorkbookConfig) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateWorkbookConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWorkbookConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateWorkbookConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateWorkbookConfig) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ListWorkbooksResponse struct {
	Data []*Workbook `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListWorkbooksResponse) GetData() []*Workbook {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListWorkbooksResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListWorkbooksResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListWorkbooksResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListWorkbooksResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListWorkbooksResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// A collection of one or more sheets
type Workbook struct {
	// ID of the Workbook.
	Id WorkbookId `json:"id" url:"id"`
	// Name of the Workbook.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Associated Space ID of the Workbook.
	SpaceId SpaceId `json:"spaceId" url:"spaceId"`
	// Associated Environment ID of the Workbook.
	EnvironmentId EnvironmentId `json:"environmentId" url:"environmentId"`
	// A list of Sheets associated with the Workbook.
	Sheets []*Sheet `json:"sheets,omitempty" url:"sheets,omitempty"`
	// A list of labels for the Workbook.
	Labels []string `json:"labels,omitempty" url:"labels,omitempty"`
	// A list of Actions associated with the Workbook.
	Actions []*Action `json:"actions,omitempty" url:"actions,omitempty"`
	// The Workbook settings.
	Settings *WorkbookConfigSettings `json:"settings,omitempty" url:"settings,omitempty"`
	// Metadata for the workbook
	Metadata interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Treatments for the workbook
	Treatments []WorkbookTreatments `json:"treatments,omitempty" url:"treatments,omitempty"`
	Namespace  *string              `json:"namespace,omitempty" url:"namespace,omitempty"`
	// Date the workbook was last updated
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	// Date the workbook was created
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// Date the workbook was created
	ExpiredAt *time.Time `json:"expiredAt,omitempty" url:"expiredAt,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *Workbook) GetId() WorkbookId {
	if w == nil {
		return ""
	}
	return w.Id
}

func (w *Workbook) GetName() *string {
	if w == nil {
		return nil
	}
	return w.Name
}

func (w *Workbook) GetSpaceId() SpaceId {
	if w == nil {
		return ""
	}
	return w.SpaceId
}

func (w *Workbook) GetEnvironmentId() EnvironmentId {
	if w == nil {
		return ""
	}
	return w.EnvironmentId
}

func (w *Workbook) GetSheets() []*Sheet {
	if w == nil {
		return nil
	}
	return w.Sheets
}

func (w *Workbook) GetLabels() []string {
	if w == nil {
		return nil
	}
	return w.Labels
}

func (w *Workbook) GetActions() []*Action {
	if w == nil {
		return nil
	}
	return w.Actions
}

func (w *Workbook) GetSettings() *WorkbookConfigSettings {
	if w == nil {
		return nil
	}
	return w.Settings
}

func (w *Workbook) GetMetadata() interface{} {
	if w == nil {
		return nil
	}
	return w.Metadata
}

func (w *Workbook) GetTreatments() []WorkbookTreatments {
	if w == nil {
		return nil
	}
	return w.Treatments
}

func (w *Workbook) GetNamespace() *string {
	if w == nil {
		return nil
	}
	return w.Namespace
}

func (w *Workbook) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *Workbook) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *Workbook) GetExpiredAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.ExpiredAt
}

func (w *Workbook) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *Workbook) UnmarshalJSON(data []byte) error {
	type embed Workbook
	var unmarshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updatedAt"`
		CreatedAt *internal.DateTime `json:"createdAt"`
		ExpiredAt *internal.DateTime `json:"expiredAt,omitempty"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = Workbook(unmarshaler.embed)
	w.UpdatedAt = unmarshaler.UpdatedAt.Time()
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	w.ExpiredAt = unmarshaler.ExpiredAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *Workbook) MarshalJSON() ([]byte, error) {
	type embed Workbook
	var marshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updatedAt"`
		CreatedAt *internal.DateTime `json:"createdAt"`
		ExpiredAt *internal.DateTime `json:"expiredAt,omitempty"`
	}{
		embed:     embed(*w),
		UpdatedAt: internal.NewDateTime(w.UpdatedAt),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
		ExpiredAt: internal.NewOptionalDateTime(w.ExpiredAt),
	}
	return json.Marshal(marshaler)
}

func (w *Workbook) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Settings for a workbook
type WorkbookConfigSettings struct {
	// Whether to track changes for this workbook. Defaults to false. Tracking changes on a workbook allows for disabling workbook and sheet actions while data in the workbook is still being processed. You must run a recordHook listener if you enable this feature.
	TrackChanges *bool `json:"trackChanges,omitempty" url:"trackChanges,omitempty"`
	// When noMappingRedirect is set to true, dragging a file into a sheet will not redirect to the mapping screen. Defaults to false.
	NoMappingRedirect *bool `json:"noMappingRedirect,omitempty" url:"noMappingRedirect,omitempty"`
	// Used to set the order of sheets in the sidebar. Sheets that are not specified will be shown after those listed.
	SheetSidebarOrder []SheetId `json:"sheetSidebarOrder,omitempty" url:"sheetSidebarOrder,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkbookConfigSettings) GetTrackChanges() *bool {
	if w == nil {
		return nil
	}
	return w.TrackChanges
}

func (w *WorkbookConfigSettings) GetNoMappingRedirect() *bool {
	if w == nil {
		return nil
	}
	return w.NoMappingRedirect
}

func (w *WorkbookConfigSettings) GetSheetSidebarOrder() []SheetId {
	if w == nil {
		return nil
	}
	return w.SheetSidebarOrder
}

func (w *WorkbookConfigSettings) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkbookConfigSettings) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkbookConfigSettings
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkbookConfigSettings(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkbookConfigSettings) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkbookResponse struct {
	Data *Workbook `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkbookResponse) GetData() *Workbook {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WorkbookResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkbookResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkbookResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkbookResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkbookResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Available treatments for a workbook
type WorkbookTreatments string

const (
	WorkbookTreatmentsExtractedFromSource WorkbookTreatments = "EXTRACTED_FROM_SOURCE"
	WorkbookTreatmentsSmallData           WorkbookTreatments = "SMALL_DATA"
)

func NewWorkbookTreatmentsFromString(s string) (WorkbookTreatments, error) {
	switch s {
	case "EXTRACTED_FROM_SOURCE":
		return WorkbookTreatmentsExtractedFromSource, nil
	case "SMALL_DATA":
		return WorkbookTreatmentsSmallData, nil
	}
	var t WorkbookTreatments
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkbookTreatments) Ptr() *WorkbookTreatments {
	return &w
}

// The updates to be made to an existing workbook
type WorkbookUpdate struct {
	// The name of the Workbook.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// An optional list of labels for the Workbook.
	Labels []string `json:"labels,omitempty" url:"labels,omitempty"`
	// The Space Id associated with the Workbook.
	SpaceId *SpaceId `json:"spaceId,omitempty" url:"spaceId,omitempty"`
	// The Environment Id associated with the Workbook.
	EnvironmentId *EnvironmentId `json:"environmentId,omitempty" url:"environmentId,omitempty"`
	// The namespace of the Workbook.
	Namespace *string `json:"namespace,omitempty" url:"namespace,omitempty"`
	// Describes shape of data as well as behavior
	Sheets  []*SheetConfigOrUpdate `json:"sheets,omitempty" url:"sheets,omitempty"`
	Actions []*Action              `json:"actions,omitempty" url:"actions,omitempty"`
	// Metadata for the workbook
	Metadata interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkbookUpdate) GetName() *string {
	if w == nil {
		return nil
	}
	return w.Name
}

func (w *WorkbookUpdate) GetLabels() []string {
	if w == nil {
		return nil
	}
	return w.Labels
}

func (w *WorkbookUpdate) GetSpaceId() *SpaceId {
	if w == nil {
		return nil
	}
	return w.SpaceId
}

func (w *WorkbookUpdate) GetEnvironmentId() *EnvironmentId {
	if w == nil {
		return nil
	}
	return w.EnvironmentId
}

func (w *WorkbookUpdate) GetNamespace() *string {
	if w == nil {
		return nil
	}
	return w.Namespace
}

func (w *WorkbookUpdate) GetSheets() []*SheetConfigOrUpdate {
	if w == nil {
		return nil
	}
	return w.Sheets
}

func (w *WorkbookUpdate) GetActions() []*Action {
	if w == nil {
		return nil
	}
	return w.Actions
}

func (w *WorkbookUpdate) GetMetadata() interface{} {
	if w == nil {
		return nil
	}
	return w.Metadata
}

func (w *WorkbookUpdate) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkbookUpdate) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkbookUpdate
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkbookUpdate(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkbookUpdate) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}
